geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')
]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='basket'),
    path('add/<int:pk>/', basketapp.basket_add, name='basket_add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='basket_remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='basket_edit'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from geekshop import settings
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', mainapp.contact, name='contacts'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),

    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path, include
from mainapp import views as mainapp

app_name = 'products'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('<int:pk>', mainapp.products, name='category'),
    path('<int:pk>/page/<int:page>', mainapp.products, name='product_paginate'),
    path('product/<int:pk>', mainapp.product, name='product')
]

geekshop/basketapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


# class BasketQuerySet(models.QuerySet):
#
#     def delete(self, *args, **kwargs):
#         for item in self:
#             item.product.quantity += item.quantity
#             item.product.save()
#         super().delete(*args, **kwargs)


class Basket(models.Model):
    # objects = BasketQuerySet.as_manager()

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        items = Basket.objects.filter(user=self.user)
        _total_quantity = sum(list(map(lambda x: x.quantity, items)))
        return _total_quantity

    @property
    def total_cost(self):
        items = Basket.objects.filter(user=self.user)
        _total_cost = sum(list(map(lambda x: x.product_cost, items)))
        return _total_cost

    @staticmethod
    def get_item(pk):
        return Basket.objects.get(pk=pk)

    # def delete(self, *args, **kwargs):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #
    #     super().delete(*args, **kwargs)

geekshop/basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse

from basketapp.models import Basket
from mainapp.models import Product


@login_required
def basket(request):
    context = {
        'basket_list': Basket.objects.filter(user=request.user).select_related()
    }
    return render(request, 'basketapp/basket.html', context)


@login_required
def basket_add(request, pk):  # pk - Product.pk
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))
    product_item = get_object_or_404(Product, pk=pk)
    basket_item = Basket.objects.filter(user=request.user, product=product_item).first()
    if not basket_item:
        basket_item = Basket(
            user=request.user,
            product=product_item
        )

    basket_item.quantity += 1
    basket_item.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):  # pk - Basket.pk
    basket_item = get_object_or_404(Basket, pk=pk)
    basket_item.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        basket_item = Basket.objects.get(pk=pk)

        if quantity > 0:
            basket_item.quantity = quantity
            basket_item.save()
        else:
            basket_item.delete()

        basket_list = Basket.objects.filter(user=request.user)
        result = render_to_string('basketapp/includes/inc_basket_list.html', {'basket_list': basket_list})
        return JsonResponse({'result': result})

geekshop/basketapp/templates/basketapp/includes/inc_basket_list.html
{% for item in basket_list %}
    <div class="basket_record">
        <img src="/media/{{ item.product.image }}" alt="">
        <span class="category_name">{{ item.category.name }}</span>
        <span class="product_name">{{ item.name }}</span>
        <span class="product_price">{{ item.product.price }}</span>
        <label>
            <input type="number" name="{{ item.pk }}" min="0" value="{{ item.quantity }}">
        </label>
        <span class="product_cost">{{ item.product_cost }}</span>
        <button class="btn btn-round" >
            <a href="{% url 'basketapp:basket_remove' item.pk %}">Удалить</a>
        </button>
    </div>
{% endfor %}
{% if basket_list %}
    В корзине {{ basket_list.0.total_quantity }} товаров на общую сумму {{ basket_list.0.total_cost|floatformat:0 }} руб. <br>
{% endif %}

geekshop/basketapp/templates/basketapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'index' %}"
           class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">домой</a></li>
    <li><a href="{% url 'products:products' %}"
           class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">продукты</a></li>
    <li><a href="{% url 'contacts' %}"
           class="{% if request.resolver_match.url_name == 'contacts' %}active{% endif %}">контакты</a></li>

    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'authapp:edit' %}">
            {% if user.first_name %}
               {{ user.first_name }}
            {% else %}
                Пользователь
            {% endif %}</a>
        </li>
        <li><a href="{% url 'authapp:logout' %}" >Выйти</a></li>
    {% else %}
        <li><a href="{% url 'authapp:register' %}" >Регистрация</a></li>
        <li><a href="{% url 'authapp:login' %}" >Войти</a></li>
    {% endif %}

</ul>
<a href="#" class="search"></a>
<a href="{% url 'basketapp:basket' %}" class="basket">
    <span>
        {% if basket %}
            ({{ basket.0.total_quantity }} шт) <br>
            {{ basket.0.total_cost|floatformat:0 }} руб

        {% endif %}
    </span>
</a>

geekshop/basketapp/templates/basketapp/includes/inc_products_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'products:category' pk=0 %}" class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}">Все</a></li>
        {% for item in links_menu %}
            <li><a href="{% url 'products:category' item.pk %}" class="{% if request.resolver_match.kwargs.pk == item.pk %}active{% endif %}">{{ item.name }}</a></li>
        {% endfor %}
    </ul>
</div>