geekshop/adminapp/urls.py
from django.urls import path
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [

    path('users/', adminapp.UsersListView.as_view(), name='users'),
    path('users/create', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>', adminapp.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>', adminapp.UsersDeleteView.as_view(), name='user_delete'),

    path('categories/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/create', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/update/<int:pk>', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/<int:pk>', adminapp.products, name='products'),
    path('products/create/<int:pk>', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>', adminapp.ProductDeleteView.as_view(), name='product_delete'),
    path('products/read/<int:pk>', adminapp.ProductDetailView.as_view(), name='product_read'),

]

geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')
]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='basket'),
    path('add/<int:pk>/', basketapp.basket_add, name='basket_add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='basket_remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='basket_edit'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from geekshop import settings
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', mainapp.contact, name='contacts'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),

    # path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from django import forms

from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):

    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryForm(forms.ModelForm):

    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

geekshop/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryForm, ProductForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users_list.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # Это функция для того что бы показать только обычные пользователи
    # def get_queryset(self):
    #     return ShopUser.objects.filter(is_superuser=True)


class UsersCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_form.html'
    # fields = '__all__'
    form_class = ShopUserRegisterForm
    success_url = reverse_lazy('adminapp:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UsersUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_form.html'
    # fields = '__all__'
    form_class = ShopUserAdminEditForm
    success_url = reverse_lazy('adminapp:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UsersDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('adminapp:users')

    # def delete(self, *args, **kwargs):
    #     self.object = self.get_object()
    #     self.object.is_active = False
    #     self.object.save()
    #
    #     return HttpResponseRedirect(self.success_url)

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductCategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories_list.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_form.html'
    # fields = '__all__'
    form_class = ProductCategoryForm
    success_url = reverse_lazy('adminapp:categories')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_form.html'
    # fields = '__all__'
    form_class = ProductCategoryForm
    success_url = reverse_lazy('adminapp:categories')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('adminapp:categories')

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.success_url)

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    category_item = get_object_or_404(ProductCategory, pk=pk)
    context = {
        'object_list': Product.objects.filter(category__pk=pk),
        'object': category_item
    }

    return render(request, 'adminapp/products_list.html', context)


# class ProductListView(ListView):
#     model = Product
#     template_name = 'adminapp/products_list.html'
#
#     def get_success_url(self):
#         product_id = self.kwargs.get('pk')
#         product = get_object_or_404(Product, pk=product_id)
#         return reverse_lazy('adminapp:products', args=[product.category.pk])
#
#     @method_decorator(user_passes_test(lambda u: u.is_superuser))
#     def dispatch(self, request, *args, **kwargs):
#         return super().dispatch(request, *args, **kwargs)

class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductForm

    def get_success_url(self):
        product_pk = self.kwargs.get('pk')
        product = get_object_or_404(Product, pk=product_pk)
        return reverse_lazy('adminapp:products', args=[product.category.pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == 'GET':
            pk = self.kwargs.get('pk')
            category_item = get_object_or_404(ProductCategory, pk=pk)
            context_data['category'] = category_item
        return context_data

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    # fields = '__all__'
    form_class = ProductForm

    def get_success_url(self):
        product_pk = self.kwargs.get('pk')
        product = get_object_or_404(Product, pk=product_pk)
        return reverse_lazy('adminapp:products', args=[product.category.pk])

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        product_id = self.kwargs.get('pk')
        product = get_object_or_404(Product, pk=product_id)
        return reverse_lazy('adminapp:products', args=[product.category.pk])

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
    <head>

        <meta charset="utf-8">
        <title>{% block title %} {{ title|title }} {% endblock %} </title>
        <link rel="icon" href="https://img.icons8.com/ios-glyphs/120/000000/mac-os.png">

        {% block css %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
            <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        {% endblock %}

        {% block js %}
            <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        {% endblock %}

    </head>
<body>
    <div class="admin_container">
        <div class="h2 text-center head">
            Admin_menu
        </div>
        <div class="admin_menu">
            <ul class="menu">
                <li>
                    <a href="{% url 'index' %}">На сайт</a>
                </li>
                <li>
                    <a href="{% url 'adminapp:users' %}"
                       class="{% if request.resolver_match.url_name == 'users' %}active{% endif %}">Пользователи</a>
                </li>
                <li>
                    <a href="{% url 'adminapp:categories' %}"
                       class="{% if request.resolver_match.url_name == 'categories' %}active{% endif %}">Категории</a>
                </li>
                <li>
                    <a href="{% url 'adminapp:categories' %}"
                       class="{% if request.resolver_match.url_name == 'products' %}active{% endif %}">
                        {% if not object.category and object.name %} > {{ object.name }}
                        {% elif object.category %} > {{ object.category.name }}
                        {% endif %}
                    </a>
                </li>

            </ul>
            <li>
                <a href="{% url 'basketapp:basket' %}" class="basket">
                    <span>
                    {% if basket %}
                        ({{ basket.0.total_quantity }} шт) <br>
                        {{ basket.0.total_cost|floatformat:0 }} руб
                    {% endif %}
                    </span>
                </a>
            </li>

        </div>
    {% block content %}
    {% endblock %}
    </div>

</body>
</html>

geekshop/adminapp/templates/adminapp/categories_list.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
    <div class="categories_list">
        <a href="{% url 'adminapp:category_create' %}" class="btn btn-primary">Создать новую категорию</a>
        {% for object in object_list %}
            <hr>
            <div class="category_record" {% if not object.is_active %}style="opacity: 0.5" {% endif %}>
            <div class="category_name">{{ object.name|title }}</div>
            <div class="category_actions">
                <a href="{% url 'adminapp:category_update' object.pk %}" class="btn btn-warning form-control">Изменить</a>
                <a href="{% url 'adminapp:category_delete' object.pk %}" class="btn btn-danger form-control">Удалить</a>
                <a href="{% url 'adminapp:products' object.pk %}" class="btn btn-primary form-control">Продукты</a>
            </div>
            <div class="category_desc">{{ object.description }}</div>
            </div>

    {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div class="login">
    <p>Вы уверены что хотите удалить категорию <span class="label-warning">{{ object.name|title }}</span> ?</p>
    <form method="post">
    {% csrf_token %}
        <input type="submit" value="Уверень!" class="btn btn-danger form-control">
    </form>
        <a href="{% url 'adminapp:categories' %}" class="btn btn-primary form-control">Нет</a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="container">
        <div class="login">
            <form class="form-horizontal " method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary form-control" value="Сохранить">
            </form>

            <a class="btn btn-info form-control" href="{% url 'adminapp:categories' %}">Перейти к списку категорий</a>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div class="login">
    <p>Вы уверены что хотите удалить продукта <span class="label-warning">{{ object.name }}</span> ?</p>
    <form method="post">
    {% csrf_token %}
        <input type="submit" value="Уверень!" class="btn btn-danger form-control">
    </form>
        <a href="{% url 'adminapp:products' object.pk %}" class="btn btn-primary form-control">Нет</a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="container">
        <div class="login">
            <form class="form-horizontal " method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary form-control" value="Сохранить">
            </form>

            {% if 'create' in request.path %}
                <a class="btn btn-info form-control" href="{% url 'adminapp:products' category.pk %}">Вернутся к списку товаров</a>
            {% elif 'update' in request.path %}
                <a class="btn btn-info form-control" href="{% url 'adminapp:products' object.category.pk %}">Вернутся к списку товаров</a>
            {% endif %}

        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<div class="product_read">
    <div class="product_name">
        Продукт<strong>{{ object.category.name|title }} {{ object.name|title }}</strong>
    </div>
    <img src="/media/{{ object.image }}" {% if not object.is_active %}style="opacity: 0.5"{% endif %} alt="{{ object.name }}">
    <div class="summary">
        <b>цена</b>
        <p>{{ object.price }} руб</p>
        <b>количество</b>
        <p>{{ object.quantity }}</p>
        <b>в каталоге</b>
        <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
        <p>
            <button>
                <a href={% url 'adminapp:product_update' object.pk %}>редактировать</a>
            </button>
        </p>
        <p>
            <button>
                <a href={% url 'adminapp:product_delete' object.pk %}>удалить</a>
            </button>
        </p>
        <p>
            <button>
                <a href={% url 'adminapp:products' object.category.pk %}>назад</a>
            </button>
        </p>
    </div>
    <div class="product_desc">
        <b>Краткая информация</b>
        <p>{{ object.short_desc }}</p>
        <br><br>
        <b>Подробная информация</b>
        <p>{{ object.description }}</p>
    </div>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products_list.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="products_list">
        <a href="{% url 'adminapp:product_create' object.pk %}" class="btn btn-primary">Добавить новый продукт</a>
        {% for object in object_list %}
            <hr>
            <div class="product_record" {% if not object.is_active %}style="opacity: 0.5" {% endif %}>
            <div class="product_name">{{ object.name }}</div>
{#            <img src="/media/{{ object.image }}" alt="">#}
            <img src="{{ object.image|media_for_products }}" alt="">
            <div class="product_actions">
                <a href="{% url 'adminapp:product_update' object.pk %}" class="btn btn-warning form-control">Изменить</a>
                <a href="{% url 'adminapp:product_delete' object.pk %}" class="btn btn-danger form-control">Удалить</a>
                <a href="{% url 'adminapp:product_read' object.pk %}" class="btn btn-primary form-control">Посмотреть</a>
            </div>
            <div class="summary">
                Цена: {{ object.price }} руб
                Количество: {{ object.quantity }} шт
            </div>
            <div class="product_desc">
                {{ object.description }}
            </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div class="login">
    <p>Вы уверены что хотите удалить пользователья <span class="label-warning">{{ object.username }}</span> ?</p>
    <form method="post">
    {% csrf_token %}
        <input type="submit" value="Уверень!" class="btn btn-danger form-control">
    </form>
        <a href="{% url 'adminapp:users' %}" class="btn btn-primary form-control">Нет</a>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="container">
        <div class="login">
            <form class="form-horizontal " method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary form-control" value="Сохранить">
            </form>

            <a class="btn btn-info form-control" href="{% url 'adminapp:users' %}">Перейти к списку пользователей</a>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/users_list.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}
{% block content %}
<div class="users_list">
    <a href="{% url 'adminapp:user_create' %}" class="btn btn-primary">Cоздать нового пользователя</a>
    {% for object in object_list %}
        <hr>
        <div class="user_record" {% if not object.is_active %}style="opacity: 0.5" {% endif %}>
{#            <div class="user_avatar_min"><img src="/media/{{ object.avatar }}" alt=""></div>#}
            <div class="user_avatar_min"><img src="{{ object.avatar|media_for_users }}" alt=""></div>
            <div class="user_role">
                {% if object.is_superuser %}
                    Администратор
                {% elif object.is_active %}
                    Пользователь
                {% else %}
                    Удаленный ползователь
                {% endif %}
                <a class="btn btn-warning form-control" href="{% url 'adminapp:user_update' object.pk %}">Изменить</a>
                <a class="btn btn-danger form-control" href="{% url 'adminapp:user_delete' object.pk %}">Удалить</a>
            </div>
            <div class="user_name">
                <p>{{ object.username }}</p>
                <p>{{ object.get_full_name }}</p>
            </div>
            <div class="user_age">{{ object.age }}</div>
        <div class="user_email">{{ object.email }}</div>
        </div>
    {% endfor %}
</div>
{% endblock %}